# # -*- coding: utf-8 -*-
# """RAG.ipynb

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/1W0jFMBvi6z6f8te4LsaVttsfN3AAZ7h-
# """

###  """**Importing libraries**"""

from youtube_transcript_api import YouTubeTranscriptApi
from youtube_transcript_api._errors import TranscriptsDisabled
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_google_genai import GoogleGenerativeAIEmbeddings,ChatGoogleGenerativeAI
from langchain_community.vectorstores import FAISS
from langchain_core.prompts import PromptTemplate
from langchain_core.runnables import RunnableParallel, RunnablePassthrough, RunnableLambda
from langchain_core.output_parsers import StrOutputParser
from dotenv import load_dotenv


load_dotenv()



###""" **Step-1 Indexing**"""

video_id = "Gfr50f6ZBvo" # only id not url
try:
    ytt_api = YouTubeTranscriptApi()
    transcript_list = ytt_api.fetch(video_id)
    transcript = " ".join(chunk.text for chunk in transcript_list)
    # print(transcript[:500])
except TranscriptsDisabled:
    print("No captions available for this video")


###""" **step 1-b Text splitting**"""

splitter = RecursiveCharacterTextSplitter(chunk_size=1000,chunk_overlap=200)
chunks = splitter.create_documents([transcript])


### """**step 1-c&d  converting to embedding and storing in vector store**"""

embeddings = GoogleGenerativeAIEmbeddings(model="models/embedding-001")
vector_store = FAISS.from_documents(chunks,embeddings)

vector_store.index_to_docstore_id

vector_store.get_by_ids(['f21995ad-3b6a-406c-8a38-6294f7f8d0df'])



### """**Ste-2 Retrieval**"""

retriever = vector_store.as_retriever(search_type='similarity',search_kwargs={"k":4})


# retriever.invoke("What is deepmind")

model = ChatGoogleGenerativeAI(model="gemini-2.5-flash")

prompt = PromptTemplate(
    template="""You are a helpful assistant.
            Answer only the provided transcript context.
            If the context is insufficient,just say you don't know.

            {context}
            Question:{question}

    """,
    input_variables=['context','question']
)




###  """**Building Chain**"""



def format_docs(retrieved_docs):
  context_text = "\n\n".join(doc.page_content for doc in retrieved_docs)
  return context_text

parallel_chain = RunnableParallel({
    'context': retriever|RunnableLambda(format_docs),
    'question':RunnablePassthrough()
})

parser = StrOutputParser()

main_chain = parallel_chain|prompt|model|parser

print(main_chain.invoke("Summarize the video"))



